### ISSUE TITLE
Clarity of descriptions / text

### ISSUE THREAD

**Issue by ElanVB** [ElanVB/indaba-pracs-2019#3]
# Sub issues:

* [x] Update language used to be more friendly to non-native English speakers #8 
* [x] Ensure that main practical goals are clearly met #9 
* [x] Tweak some descriptions for better clarity #10 
* [x] Ensure all relevant terminology is introduced prior to it being needed (or at least link to a source) #11
